# Generated by Django 3.1.4 on 2020-12-18 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credencial', models.CharField(default=None, max_length=50, null=True)),
                ('fecha_ultimoregistro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fecha_registra', models.DateTimeField()),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeronaves_revision', to='marcial.aeronave')),
                ('pasajeros', models.ManyToManyField(related_name='revisiones', to='marcial.Pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Aeronave_Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fecha_registra', models.DateTimeField(auto_now=True)),
                ('ingresa_eronave', models.BooleanField()),
                ('aeronave', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aeronaves_aeropasajero', to='marcial.pasajero')),
                ('pasajero', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros_aeropasajero', to='marcial.aeronave')),
            ],
        ),
        migrations.AddField(
            model_name='aeronave',
            name='nave_destino',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='naves_destino', to='marcial.nave'),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='nave_origen',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='naves_origen', to='marcial.nave'),
        ),
    ]
