# Generated by Django 3.1.4 on 2020-12-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave_pasajero',
            name='aeronave',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aeronaves_aeropasajero', to='marcial.aeronave'),
        ),
        migrations.AlterField(
            model_name='aeronave_pasajero',
            name='pasajero',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros_aeropasajero', to='marcial.pasajero'),
        ),
    ]
