# Generated by Django 2.2.6 on 2020-12-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave_pasajero',
            name='ingresa_aeronave',
            field=models.BooleanField(),
        ),
    ]
