# Generated by Django 2.2.6 on 2020-12-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcial', '0002_auto_20201218_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='lista_pasajeros',
            field=models.ManyToManyField(related_name='listado_pasajeros', to='marcial.Pasajero'),
        ),
    ]
