# Generated by Django 3.1.4 on 2020-12-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcial', '0003_remove_aeronave_pasajero_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave_pasajero',
            name='ingresa_eronave',
            field=models.BooleanField(default=False),
        ),
    ]
